#!/bin/bash

########################################################################
#   airtools [-h] <args>
#
#   a wrapper around airtools-gui.jar
#
########################################################################
VERSION="0.2"
VINFO="T. Lehmann, Mar. 2019"
PINFO="\
    options:
      h         show this help text
      l         prefer java program from users bin directory
      args      program arguments passed over to java program
"
CHANGELOG="
    0.2  - 16 Mar 2019
        * added option -l to prefer java program from users bin directory
        * improved error checking and messages

    0.1  - 10 Nov 2018
        * initial version
"


#--------------------
#   user definitions
#--------------------
jar=airtools-gui.jar
datadir=/usr/share/airtools


#--------------------
#   get options
#--------------------
cmdline="$(basename $0) $@"  # preserve command line
prefer_local_bin=""
testonly=""
showhelp=""
for i in $(seq 1 3)
do
    (test "$1" == "-h" || test "$1" == "--help") && showhelp=1 && shift 1
    test "$1" == "-l" && prefer_local_bin=1 && shift 1
    test "$1" == "-t" && testonly=1 && shift 1
done


#--------------------
#   checkings
#--------------------
test "$showhelp" &&
    echo $(basename $0)"   $VERSION   $VINFO" >&2 &&
    printf "$PINFO" >&2 &&
    exit -1

# find program jar file
prog=""
test -e "$datadir/$jar" && prog="$datadir/$jar"
if [ "$prefer_local_bin" ]
then
    test -e $HOME/bin/$jar      && prog=$HOME/bin/$jar
    test -e $HOME/bin/home/$jar && prog=$HOME/bin/home/$jar
fi
if [ -z "$prog" ]
then
    msg="Unable to find $jar"
    type -p yad >/dev/null &&
        yad --title "Error" --window-icon=none --image=gtk-dialog-error --no-buttons --text "\n  $msg" && exit 1
    type -p zenity >/dev/null &&
        zenity --error --text "\n  $msg" && exit 1
    notify-send -u critical -i gtk-dialog-error "$msg"
    exit 1
fi


#--------------------
#   start
#--------------------
# set Java 8 runtime
# (currently there are problems using Java 11 which is the default java
# on Ubuntu 18.04)
JAVA_HOME=$(update-alternatives --list java | grep -E "java-8|jdk-8|jre-8" | head -1 | \
    sed -e 's,/bin/java$,,')
test -z "$JAVA_HOME" &&
    echo "ERROR: unable to find Java 8 runtime." >&2 &&
    exit 255

# start java program
if [ "$testonly" ]
then
    echo $JAVA_HOME/bin/java -jar $prog "$@"
else
    $JAVA_HOME/bin/java -jar $prog "$@"
fi
